name: flutter_rosutils
description: A Flutter package that helps to generate boilerplate code for roslib applications
version: 0.0.1
author: Tim Whiting <tim.a.whiting@gmail.com>
homepage: https://github.com/TimWhiting/flutter_rosutils

environment:
  sdk: ">=2.6.0-dev.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: